### PR TITLE
Initial work streams merge

### PR DESCRIPTION
**Pull request by ghost**
Hi this has dockerisation, dummy page navigation, integration tests, initial static code testing tools & sonar.  Let me know...

### CODE REVIEW

**Comment by DougC** [comment]
The .gradle and .idea directories shouldn't be committed to git as they're specific to the dev machine. Can you create a .gitignore file and add those directories to it and remove the files from the commit?

**Comment by DougC** [comment]
Not to worry, I did the .gitignore thing :-)

**Comment by DougC** [comment]
Looks good otherwise, go ahead and merge if you're happy with the .gitignore change.

**Review by DougC — APPROVED** [review]

**Comment by BenKDishman** [comment]
Cheers Doug, I'll take note that if I don't respond quickly you'll do it for me  ;-)

**Pull request merged**
