### PR TITLE
1116 - view opportunity details

### PR DESCRIPTION
**Pull request by venkata999**
Hi Guys 
I added code for Java front end for this Sprint. Please have a look.

### CODE REVIEW

**Comment by BenKDishman** [comment]
CI check failing?  Looks like a dependancy issue & it builds & runs on my machine so probably a devops issue !?  Not looking on a Saturday afternoon just happened to on PC looking at something else... Looks good to me, although if it's a quick and simple job might be worth formatting the amount from 2000.0 to either 2000 or 2000.00 (probably 2000 depending on prototypes)

**Comment by DougC** [comment]
Don't worry about the circleci build - I set that up but it isn't working for some reason and I haven't had a chance to find out why. I've disabled it for the moment.

**Review by DougC — APPROVED** [review]
Added some code cleanup. Looks ready to merge. Only suggestion is removing the boilerplate comments of the controller methods - they don't say anything that the method signature don't already say.

**Comment by venkata999** [comment]
Thanks Guys

**Pull request merged**
